spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**

        - id: practicien-service
          uri: lb://practicien-service
          predicates:
            - Path=/practiciens/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true