spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**
          filters:
            - RewritePath=/patients(?<segment>/?.*), /patients/$\{segment}
            - name: CircuitBreaker
              args:
                name: circuitBreakerInstance
                fallbackUri: forward:/fallback/patients

        - id: practicien-service
          uri: lb://practicien-service
          predicates:
            - Path=/practiciens/**
          filters:
            - RewritePath=/practitioners(?<segment>/?.*), /practitioners/$\{segment}
            - name: CircuitBreaker
              args:
                name: circuitBreakerInstance
                fallbackUri: forward:/fallback/practitioners

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true