apiVersion: apps/v1
kind: Deployment
metadata:
  name: practitioner-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practitioner-service
  template:
    metadata:
      labels:
        app: practitioner-service
    spec:
      containers:
        - name: practitioner-service
          image: practitioner-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
