eureka:
  client:
    service-url:
      defaultZone: http://eureka-service.default.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: patient-service

resilience4j:
  circuitbreaker:
    instances:
      patientService:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5

  ratelimiter:
    instances:
      patientService:
        limitRefreshPeriod: 1s
        limitForPeriod: 5
        timeoutDuration: 0s
